# Generated by Django 5.1 on 2024-08-12 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huddle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
