# Generated by Django 5.0.8 on 2024-08-13 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huddle', '0002_rename_crated_at_item_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-created_at',)},
        ),
    ]
