/* == index.js
като Master Layout в Archicad

Тук се композират общите за аппа елменти 
  - navbar, footer
  - метаданни за всички страници, език, шрифтове

https://nextjs.org/docs/app/building-your-application/routing/layouts-and-templates 
*/

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Y Next Tool app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Header за всички страници */}
        <header>
          <h1 className="font-sans text-center text-base bg-orange-300 p-2 text-black font-bold mb-4">
            Nav bar
          </h1>
        </header>

        {children}
      </body>
    </html>
  );
}
