mylist = iter(["apple", "banana", "cherry"])
x = next(mylist, "end of list")
print(x)
x = next(mylist, "end of list")
print(x)
x = next(mylist, "end of list")
print(x)
x = next(mylist, "end of list")
print(x)